-- Auto-generated by warehouse/dbt/generate_staging_model.py
-- from contracts/schemas.py v1.0.1. Re-run and diff if the contract changes.

with source as (
    select * from {{ source('nidd_raw', 'silver_flows') }}
),

renamed as (
    select
        event_id,
        ingestion_timestamp,
        schema_version,
        dur as dur,
        proto as proto,
        cause as cause,
        state as state,
        stos as stos,
        dtos as dtos,
        sdsb as sdsb,
        ddsb as ddsb,
        sttl as sttl,
        dttl as dttl,
        shops as shops,
        dhops as dhops,
        totpkts as totpkts,
        srcpkts as srcpkts,
        dstpkts as dstpkts,
        totbytes as totbytes,
        srcbytes as srcbytes,
        dstbytes as dstbytes,
        smeanpktsz as smeanpktsz,
        dmeanpktsz as dmeanpktsz,
        load as load,
        srcload as srcload,
        dstload as dstload,
        loss as loss,
        srcloss as srcloss,
        dstloss as dstloss,
        ploss as ploss,
        srcgap as srcgap,
        dstgap as dstgap,
        rate as rate,
        srcrate as srcrate,
        dstrate as dstrate,
        srcwin as srcwin,
        dstwin as dstwin,
        srctcpbase as srctcpbase,
        dsttcpbase as dsttcpbase,
        tcprtt as tcprtt,
        synack as synack,
        ackdat as ackdat,
        is_tcp,
        has_dst_reply,
        label,
        attack_type,
        attack_tool
    from source
)

select * from renamed
