-- Auto-generated by warehouse/generate_ddl.py from contracts/schemas.py v1.0.1
-- Re-run that script and diff if the contract changes.

CREATE WAREHOUSE IF NOT EXISTS NIDD_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS NIDD_DB;
CREATE SCHEMA IF NOT EXISTS NIDD_DB.SILVER;

USE WAREHOUSE NIDD_WH;
USE DATABASE NIDD_DB;
USE SCHEMA SILVER;

CREATE TABLE IF NOT EXISTS SILVER_FLOWS (
    event_id             VARCHAR(64) NOT NULL,
    ingestion_timestamp  TIMESTAMP_NTZ NOT NULL,
    schema_version       VARCHAR(16) NOT NULL,
    Dur                  FLOAT NOT NULL,
    Proto                VARCHAR(64) NOT NULL,
    Cause                VARCHAR(64) NOT NULL,
    State                VARCHAR(64) NOT NULL,
    sTos                 FLOAT,
    dTos                 FLOAT,
    sDSb                 VARCHAR(64),
    dDSb                 VARCHAR(64),
    sTtl                 FLOAT,
    dTtl                 FLOAT,
    sHops                FLOAT,
    dHops                FLOAT,
    TotPkts              NUMBER(38,0) NOT NULL,
    SrcPkts              NUMBER(38,0) NOT NULL,
    DstPkts              NUMBER(38,0) NOT NULL,
    TotBytes             NUMBER(38,0) NOT NULL,
    SrcBytes             NUMBER(38,0) NOT NULL,
    DstBytes             NUMBER(38,0) NOT NULL,
    sMeanPktSz           FLOAT NOT NULL,
    dMeanPktSz           FLOAT NOT NULL,
    Load                 FLOAT NOT NULL,
    SrcLoad              FLOAT NOT NULL,
    DstLoad              FLOAT NOT NULL,
    Loss                 NUMBER(38,0) NOT NULL,
    SrcLoss              NUMBER(38,0) NOT NULL,
    DstLoss              NUMBER(38,0) NOT NULL,
    pLoss                FLOAT NOT NULL,
    SrcGap               FLOAT,
    DstGap               FLOAT,
    Rate                 FLOAT NOT NULL,
    SrcRate              FLOAT NOT NULL,
    DstRate              FLOAT NOT NULL,
    SrcWin               FLOAT,
    DstWin               FLOAT,
    SrcTCPBase           FLOAT,
    DstTCPBase           FLOAT,
    TcpRtt               FLOAT NOT NULL,
    SynAck               FLOAT NOT NULL,
    AckDat               FLOAT NOT NULL,
    is_tcp               NUMBER(1,0) NOT NULL,
    has_dst_reply        NUMBER(1,0) NOT NULL,
    Label                VARCHAR(16) NOT NULL,
    attack_type          VARCHAR(32) NOT NULL,
    attack_tool          VARCHAR(32) NOT NULL,
    loaded_at            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
