"""
warehouse/dbt/generate_staging_model.py
==========================================
Generates models/staging/stg_flows.sql FROM contracts/schemas.py.
Snowflake stores unquoted identifiers as UPPERCASE (see create_silver_flows.sql),
so this model selects each uppercase source column and aliases it to a clean
lowercase name for the rest of the dbt project to use.

Usage:
    python3 warehouse/dbt/generate_staging_model.py > warehouse/dbt/nidd_dw/models/staging/stg_flows.sql
"""

import sys

sys.path.append(".")
from contracts.schemas import FEATURE_SCHEMA, LABEL_COLUMNS  # noqa: E402


def generate_staging_sql() -> str:
    lines = [
        "-- Auto-generated by warehouse/dbt/generate_staging_model.py",
        "-- from contracts/schemas.py v1.0.1. Re-run and diff if the contract changes.",
        "",
        "with source as (",
        "    select * from {{ source('nidd_raw', 'silver_flows') }}",
        "),",
        "",
        "renamed as (",
        "    select",
        "        event_id,",
        "        ingestion_timestamp,",
        "        schema_version,",
    ]

    for f in FEATURE_SCHEMA:
        lines.append(f"        {f.name.lower()} as {f.name.lower()},")

    lines.append("        is_tcp,")
    lines.append("        has_dst_reply,")
    lines.append("        label,")
    lines.append("        attack_type,")
    lines.append("        attack_tool")
    lines.append("    from source")
    lines.append(")")
    lines.append("")
    lines.append("select * from renamed")

    return "\n".join(lines)


if __name__ == "__main__":
    print(generate_staging_sql())
